In [1]:
import pandas as pd
import pandas_datareader.data as web

In [2]:
info = pd.DataFrame(columns=['Name', 'Unit', 'Construction', 'Description'])
info.loc['Mkt-RF'] = ['Market', 'Excess Return', 'Market-cap-weighted', 'US Equities']
info.loc['SMB'] = ['Size', 'Excess Return', 'Small Minus Big', 'Long small stocks and short big stocks']
info.loc['HML'] = ['Value', 'Excess Return', 'High Minus Low', 'Long value (high book-to-market) stocks and short growth (low book-to-market) stocks']
info.loc['RF'] = ['Risk-free rate', 'Total Return', 'Tbills', '']
info

,Name,Unit,Construction,Description
Mkt-RF,Market,Excess Return,Market-cap-weighted,US Equities
SMB,Size,Excess Return,Small Minus Big,Long small stocks and short big stocks
HML,Value,Excess Return,High Minus Low,Long value (high book-to-market) stocks and sh...
RF,Risk-free rate,Total Return,Tbills,

In [3]:
STARTDATE = '19260101'
ENDDATE = '20220930'

rawdata = web.DataReader('F-F_Research_Data_Factors', data_source='famafrench',start=STARTDATE,end=ENDDATE)
facs = rawdata[0] / 100
# convert the yyyy-mm to timestamp object. default is to put first of month, but should be end of month
facs = facs.to_timestamp().resample('M').last()
facs

            Mkt-RF     SMB     HML      RF
Date
1926-07-31  0.0296 -0.0256 -0.0243  0.0022
1926-08-31  0.0264 -0.0117  0.0382  0.0025
1926-09-30  0.0036 -0.0140  0.0013  0.0023
1926-10-31 -0.0324 -0.0009  0.0070  0.0032
1926-11-30  0.0253 -0.0010 -0.0051  0.0031
...            ...     ...     ...     ...
2022-04-30 -0.0946 -0.0141  0.0619  0.0001
2022-05-31 -0.0034 -0.0185  0.0841  0.0003
2022-06-30 -0.0843  0.0209 -0.0597  0.0006
2022-07-31  0.0957  0.0281 -0.0410  0.0008
2022-08-31 -0.0378  0.0139  0.0031  0.0019

[1154 rows x 4 columns]

In [4]:
rawdata = web.DataReader('25_Portfolios_5x5', data_source='famafrench',start=STARTDATE,end=ENDDATE)
rets = rawdata[0] / 100
# convert the yyyy-mm to timestamp object. default is to put first of month, but should be end of month
rets = rets.to_timestamp().resample('M').last()
rets

,SMALL LoBM,ME1 BM2,ME1 BM3,ME1 BM4,SMALL HiBM,ME2 BM1,ME2 BM2,ME2 BM3,ME2 BM4,ME2 BM5,...,ME4 BM1,ME4 BM2,ME4 BM3,ME4 BM4,ME4 BM5,BIG LoBM,ME5 BM2,ME5 BM3,ME5 BM4,BIG HiBM
Date,,,,,,,,,,,,,,,,,,,,,
1926-07-31,0.058248,-0.017006,0.004875,-0.014580,0.020534,0.012077,0.024192,0.004926,-0.026049,-0.003344,...,0.015893,0.015278,0.012978,0.002727,0.024678,0.034539,0.060902,0.020266,0.031111,0.005623
1926-08-31,-0.020206,-0.080282,0.013796,0.014606,0.083968,0.023618,-0.011849,0.040084,0.005038,0.061675,...,0.013336,0.038730,0.020021,0.021706,0.053422,0.010124,0.041903,0.020131,0.054849,0.077576
1926-09-30,-0.048291,-0.026154,-0.043417,-0.032729,0.008649,-0.026540,-0.012618,0.010829,-0.035480,-0.009401,...,0.010923,-0.005250,-0.017636,0.014646,0.008730,-0.012906,0.036538,0.000950,-0.007487,-0.024284
1926-10-31,-0.093729,-0.035519,-0.034948,0.034413,-0.025476,-0.028069,-0.032663,-0.050745,-0.080191,-0.013213,...,-0.033361,-0.026559,-0.021070,-0.031051,-0.053525,-0.027413,-0.030071,-0.022437,-0.046719,-0.058129
1926-11-30,0.055888,0.041877,0.024623,-0.044494,0.005362,0.031033,-0.023690,0.030078,0.051546,0.027292,...,0.034448,0.023887,0.037335,0.049320,0.018213,0.042946,0.025326,0.015204,0.036619,0.025636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-04-30,-0.161458,-0.132365,-0.099863,-0.063449,-0.040988,-0.181950,-0.120671,-0.085393,-0.062858,-0.059654,...,-0.107264,-0.080398,-0.048345,-0.056840,-0.070521,-0.108609,-0.092140,-0.071498,-0.055172,-0.074225
2022-05-31,-0.058265,-0.035601,-0.009777,-0.001506,0.029569,-0.032936,-0.028180,0.020090,0.040419,0.057494,...,-0.029505,0.011418,0.040600,0.008937,0.082899,-0.030113,-0.003170,0.028100,0.064726,0.064003
2022-06-30,-0.066490,-0.042722,-0.042452,-0.065665,-0.098769,-0.020535,-0.062438,-0.067874,-0.062183,-0.129730,...,-0.072856,-0.095073,-0.111652,-0.100982,-0.132412,-0.078059,-0.055254,-0.087814,-0.120979,-0.121789
2022-07-31,0.153839,0.129453,0.082644,0.096279,0.057074,0.127958,0.136533,0.116312,0.099950,0.092214,...,0.131755,0.109898,0.069970,0.095202,0.061561,0.127225,0.055066,0.041833,0.073500,0.067965
2022-08-31,0.038098,-0.001388,0.005269,-0.000219,-0.002621,0.036693,-0.008214,-0.044867,-0.038408,-0.024716,...,-0.025402,-0.030861,-0.039483,-0.026975,-0.003650,-0.053349,-0.031101,-0.019065,0.000550,-0.030467

In [5]:
with pd.ExcelWriter('../data/dfa_analysis_data.xlsx') as writer:  
    info.to_excel(writer, sheet_name= 'descriptions')
    facs.to_excel(writer, sheet_name='factors')
    rets.to_excel(writer, sheet_name='portfolios (total returns)')